// Burger constructor
export const BURGER_CONSTRUCTOR_ADD_ITEM: 'BURGER_CONSTRUCTOR_ADD_ITEM' = 'BURGER_CONSTRUCTOR_ADD_ITEM';
export const BURGER_CONSTRUCTOR_REMOVE_ITEM: 'BURGER_CONSTRUCTOR_REMOVE_ITEM' = 'BURGER_CONSTRUCTOR_REMOVE_ITEM';
export const BURGER_CONSTRUCTOR_MOVE_ITEM: 'BURGER_CONSTRUCTOR_MOVE_ITEM' = 'BURGER_CONSTRUCTOR_MOVE_ITEM';
export const BURGER_CONSTRUCTOR_SET_BUN: 'BURGER_CONSTRUCTOR_SET_BUN' = 'BURGER_CONSTRUCTOR_SET_BUN';
export const BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR: 'BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR' = 'BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR';


// Ingredietns
export const INGREDIETNS_REQUEST: 'INGREDIETNS_REQUEST' = 'INGREDIETNS_REQUEST';
export const INGREDIETNS_SUCCESS: 'INGREDIETNS_SUCCESS' = 'INGREDIETNS_SUCCESS';
export const INGREDIETNS_FAILURE: 'INGREDIETNS_FAILURE' = 'INGREDIETNS_FAILURE';
export const INGREDIETNS_INCREASE_INGREDIENT_COUNT: 'INGREDIETNS_INCREASE_INGREDIENT_COUNT' = 'INGREDIETNS_INCREASE_INGREDIENT_COUNT';
export const INGREDIETNS_DECREASE_INGREDIENT_COUNT: 'INGREDIETNS_DECREASE_INGREDIENT_COUNT' = 'INGREDIETNS_DECREASE_INGREDIENT_COUNT';
export const INGREDIETNS_RESET_INGREDIENTS_COUNTER: 'INGREDIETNS_RESET_INGREDIENTS_COUNTER' = 'INGREDIETNS_RESET_INGREDIENTS_COUNTER';


// Modal
export const MODAL_OPEN_MODAL: 'MODAL_OPEN_MODAL' = 'MODAL_OPEN_MODAL';
export const MODAL_CLOSE_MODAL: 'MODAL_CLOSE_MODAL' = 'MODAL_CLOSE_MODAL';


// Order (from burger constructor)
export const ORDER_REQUEST: 'ORDER_REQUEST' = 'ORDER_REQUEST';
export const ORDER_SUCCESS: 'ORDER_SUCCESS' = 'ORDER_SUCCESS';
export const ORDER_FAILURE: 'ORDER_FAILURE' = 'ORDER_FAILURE';
export const ORDER_RESET_REQUEST_STATUS: 'ORDER_RESET_REQUEST_STATUS' = 'ORDER_RESET_REQUEST_STATUS';


// User
export const USER_SET_USER: 'USER_SET_USER' = 'USER_SET_USER';

export const USER_SET_REGISTER_REQUEST: 'USER_SET_REGISTER_REQUEST' = 'USER_SET_REGISTER_REQUEST';
export const USER_SET_REGISTER_SUCCESS: 'USER_SET_REGISTER_SUCCESS' = 'USER_SET_REGISTER_SUCCESS';
export const USER_SET_REGISTER_FAILURE: 'USER_SET_REGISTER_FAILURE' = 'USER_SET_REGISTER_FAILURE';

export const USER_SET_LOGIN_REQUEST: 'USER_SET_LOGIN_REQUEST' = 'USER_SET_LOGIN_REQUEST';
export const USER_SET_LOGIN_SUCCESS: 'USER_SET_LOGIN_SUCCESS' = 'USER_SET_LOGIN_SUCCESS';
export const USER_SET_LOGIN_FAILURE: 'USER_SET_LOGIN_FAILURE' = 'USER_SET_LOGIN_FAILURE';

export const USER_SET_LOGOUT_REQUEST: 'USER_SET_LOGOUT_REQUEST' = 'USER_SET_LOGOUT_REQUEST';
export const USER_SET_LOGOUT_SUCCESS: 'USER_SET_LOGOUT_SUCCESS' = 'USER_SET_LOGOUT_SUCCESS';
export const USER_SET_LOGOUT_FAILURE: 'USER_SET_LOGOUT_FAILURE' = 'USER_SET_LOGOUT_FAILURE';

export const USER_SET_GET_USER_REQUEST: 'USER_SET_GET_USER_REQUEST' = 'USER_SET_GET_USER_REQUEST';
export const USER_SET_GET_USER_SUCCESS: 'USER_SET_GET_USER_SUCCESS' = 'USER_SET_GET_USER_SUCCESS';
export const USER_SET_GET_USER_FAILURE: 'USER_SET_GET_USER_FAILURE' = 'USER_SET_GET_USER_FAILURE';

export const USER_SET_PATCH_USER_REQUEST: 'USER_SET_PATCH_USER_REQUEST' = 'USER_SET_PATCH_USER_REQUEST';
export const USER_SET_PATCH_USER_SUCCESS: 'USER_SET_PATCH_USER_SUCCESS' = 'USER_SET_PATCH_USER_SUCCESS';
export const USER_SET_PATCH_USER_FAILURE: 'USER_SET_PATCH_USER_FAILURE' = 'USER_SET_PATCH_USER_FAILURE';


// User forms like Login, ResetPassword ect.
// Form ForgotPassword
export const FORM_FORGOT_PASSWORD_SET_VALUE: 'FORM_FORGOT_PASSWORD_SET_VALUE' = 'FORM_FORGOT_PASSWORD_SET_VALUE';
export const FORM_FORGOT_PASSWORD_SET_VERIFIED_EMAIL: 'FORM_FORGOT_PASSWORD_SET_VERIFIED_EMAIL' = 'FORM_FORGOT_PASSWORD_SET_VERIFIED_EMAIL';
export const FORM_FORGOT_PASSWORD_CLEAR_FORM: 'FORM_FORGOT_PASSWORD_CLEAR_FORM' = 'FORM_FORGOT_PASSWORD_CLEAR_FORM';
export const FORM_FORGOT_PASSWORD_REQUEST: 'FORM_FORGOT_PASSWORD_REQUEST' = 'FORM_FORGOT_PASSWORD_REQUEST';
export const FORM_FORGOT_PASSWORD_SUCCESS: 'FORM_FORGOT_PASSWORD_SUCCESS' = 'FORM_FORGOT_PASSWORD_SUCCESS';
export const FORM_FORGOT_PASSWORD_FAILURE: 'FORM_FORGOT_PASSWORD_FAILURE' = 'FORM_FORGOT_PASSWORD_FAILURE';

// Form Login
export const FORM_LOGIN_SET_VALUE: 'FORM_LOGIN_SET_VALUE' = 'FORM_LOGIN_SET_VALUE';
export const FORM_LOGIN_CLEAR_FORM: 'FORM_LOGIN_CLEAR_FORM' = 'FORM_LOGIN_CLEAR_FORM';

// Form Profile
export const FORM_PROFILE_SET_INITIAL_VALUE: 'FORM_PROFILE_SET_INITIAL_VALUE' = 'FORM_PROFILE_SET_INITIAL_VALUE';
export const FORM_PROFILE_SET_VALUE: 'FORM_PROFILE_SET_VALUE' = 'FORM_PROFILE_SET_VALUE';
export const FORM_PROFILE_RESET_FORM: 'FORM_PROFILE_RESET_FORM' = 'FORM_PROFILE_RESET_FORM';
export const FORM_PROFILE_CLEAR_FORM: 'FORM_PROFILE_CLEAR_FORM' = 'FORM_PROFILE_CLEAR_FORM';

// Form Register
export const FORM_REGISTER_SET_VALUE: 'FORM_REGISTER_SET_VALUE' = 'FORM_REGISTER_SET_VALUE';
export const FORM_REGISTER_CLEAR_FORM: 'FORM_REGISTER_CLEAR_FORM' = 'FORM_REGISTER_CLEAR_FORM';

// Form Reset password
export const FORM_RESET_PASSWORD_SET_VALUE: 'FORM_RESET_PASSWORD_SET_VALUE' = 'FORM_RESET_PASSWORD_SET_VALUE';
export const FORM_RESET_PASSWORD_CLEAR_FORM: 'FORM_RESET_PASSWORD_CLEAR_FORM' = 'FORM_RESET_PASSWORD_CLEAR_FORM';
export const FORM_RESET_PASSWORD_REQUEST: 'FORM_RESET_PASSWORD_REQUEST' = 'FORM_RESET_PASSWORD_REQUEST';
export const FORM_RESET_PASSWORD_SUCCESS: 'FORM_RESET_PASSWORD_SUCCESS' = 'FORM_RESET_PASSWORD_SUCCESS';
export const FORM_RESET_PASSWORD_FAILURE: 'FORM_RESET_PASSWORD_FAILURE' = 'FORM_RESET_PASSWORD_FAILURE';


// Websocket
export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
