// Burger constructor
export const BURGER_CONSTRUCTOR_ADD_ITEM: 'BURGER_CONSTRUCTOR_ADD_ITEM' = 'BURGER_CONSTRUCTOR_ADD_ITEM';
export const BURGER_CONSTRUCTOR_REMOVE_ITEM: 'BURGER_CONSTRUCTOR_REMOVE_ITEM' = 'BURGER_CONSTRUCTOR_REMOVE_ITEM';
export const BURGER_CONSTRUCTOR_MOVE_ITEM: 'BURGER_CONSTRUCTOR_MOVE_ITEM' = 'BURGER_CONSTRUCTOR_MOVE_ITEM';
export const BURGER_CONSTRUCTOR_SET_BUN: 'BURGER_CONSTRUCTOR_SET_BUN' = 'BURGER_CONSTRUCTOR_SET_BUN';
export const BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR: 'BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR' = 'BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR';


// Ingredietns
export const INGREDIETNS_REQUEST: 'INGREDIETNS_REQUEST' = 'INGREDIETNS_REQUEST';
export const INGREDIETNS_SUCCESS: 'INGREDIETNS_SUCCESS' = 'INGREDIETNS_SUCCESS';
export const INGREDIETNS_FAILURE: 'INGREDIETNS_FAILURE' = 'INGREDIETNS_FAILURE';
export const INGREDIETNS_INCREASE_INGREDIENT_COUNT: 'INGREDIETNS_INCREASE_INGREDIENT_COUNT' = 'INGREDIETNS_INCREASE_INGREDIENT_COUNT';
export const INGREDIETNS_DECREASE_INGREDIENT_COUNT: 'INGREDIETNS_DECREASE_INGREDIENT_COUNT' = 'INGREDIETNS_DECREASE_INGREDIENT_COUNT';
export const INGREDIETNS_RESET_INGREDIENTS_COUNTER: 'INGREDIETNS_RESET_INGREDIENTS_COUNTER' = 'INGREDIETNS_RESET_INGREDIENTS_COUNTER';


// User forms like Login, ResetPassword ect.
// Form ForgotPassword
export const FORM_FORGOT_PASSWORD_SET_VALUE: 'FORM_FORGOT_PASSWORD_SET_VALUE' = 'FORM_FORGOT_PASSWORD_SET_VALUE';
export const FORM_FORGOT_PASSWORD_SET_VERIFIED_EMAIL: 'FORM_FORGOT_PASSWORD_SET_VERIFIED_EMAIL' = 'FORM_FORGOT_PASSWORD_SET_VERIFIED_EMAIL';
export const FORM_FORGOT_PASSWORD_CLEAR_FORM: 'FORM_FORGOT_PASSWORD_CLEAR_FORM' = 'FORM_FORGOT_PASSWORD_CLEAR_FORM';
export const FORM_FORGOT_PASSWORD_REQUEST: 'FORM_FORGOT_PASSWORD_REQUEST' = 'FORM_FORGOT_PASSWORD_REQUEST';
export const FORM_FORGOT_PASSWORD_SUCCESS: 'FORM_FORGOT_PASSWORD_SUCCESS' = 'FORM_FORGOT_PASSWORD_SUCCESS';
export const FORM_FORGOT_PASSWORD_FAILURE: 'FORM_FORGOT_PASSWORD_FAILURE' = 'FORM_FORGOT_PASSWORD_FAILURE';

// Form Login
export const FORM_LOGIN_SET_VALUE: 'FORM_LOGIN_SET_VALUE' = 'FORM_LOGIN_SET_VALUE';
export const FORM_LOGIN_CLEAR_FORM: 'FORM_LOGIN_CLEAR_FORM' = 'FORM_LOGIN_CLEAR_FORM';

// Form Profile
export const FORM_PROFILE_SET_INITIAL_VALUE: 'FORM_PROFILE_SET_INITIAL_VALUE' = 'FORM_PROFILE_SET_INITIAL_VALUE';
export const FORM_PROFILE_SET_VALUE: 'FORM_PROFILE_SET_VALUE' = 'FORM_PROFILE_SET_VALUE';
export const FORM_PROFILE_RESET_FORM: 'FORM_PROFILE_RESET_FORM' = 'FORM_PROFILE_RESET_FORM';
export const FORM_PROFILE_CLEAR_FORM: 'FORM_PROFILE_CLEAR_FORM' = 'FORM_PROFILE_CLEAR_FORM';

// Form Register
export const FORM_REGISTER_SET_VALUE: 'FORM_REGISTER_SET_VALUE' = 'FORM_REGISTER_SET_VALUE';
export const FORM_REGISTER_CLEAR_FORM: 'FORM_REGISTER_CLEAR_FORM' = 'FORM_REGISTER_CLEAR_FORM';

// Form Reset password
export const FORM_RESET_PASSWORD_SET_VALUE: 'FORM_RESET_PASSWORD_SET_VALUE' = 'FORM_RESET_PASSWORD_SET_VALUE';
export const FORM_RESET_PASSWORD_CLEAR_FORM: 'FORM_RESET_PASSWORD_CLEAR_FORM' = 'FORM_RESET_PASSWORD_CLEAR_FORM';
export const FORM_RESET_PASSWORD_REQUEST: 'FORM_RESET_PASSWORD_REQUEST' = 'FORM_RESET_PASSWORD_REQUEST';
export const FORM_RESET_PASSWORD_SUCCESS: 'FORM_RESET_PASSWORD_SUCCESS' = 'FORM_RESET_PASSWORD_SUCCESS';
export const FORM_RESET_PASSWORD_FAILURE: 'FORM_RESET_PASSWORD_FAILURE' = 'FORM_RESET_PASSWORD_FAILURE';
