// Burger constructor
export const BURGER_CONSTRUCTOR_ADD_ITEM: 'BURGER_CONSTRUCTOR_ADD_ITEM' = 'BURGER_CONSTRUCTOR_ADD_ITEM';
export const BURGER_CONSTRUCTOR_REMOVE_ITEM: 'BURGER_CONSTRUCTOR_REMOVE_ITEM' = 'BURGER_CONSTRUCTOR_REMOVE_ITEM';
export const BURGER_CONSTRUCTOR_MOVE_ITEM: 'BURGER_CONSTRUCTOR_MOVE_ITEM' = 'BURGER_CONSTRUCTOR_MOVE_ITEM';
export const BURGER_CONSTRUCTOR_SET_BUN: 'BURGER_CONSTRUCTOR_SET_BUN' = 'BURGER_CONSTRUCTOR_SET_BUN';
export const BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR: 'BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR' = 'BURGER_CONSTRUCTOR_CLEAR_CONSTRUCTOR';
